export const NEWSLETTER_LIST_REQUEST = 'NEWSLETTER_LIST_REQUEST';
export const NEWSLETTER_LIST_SUCCESS = 'NEWSLETTER_LIST_SUCCESS';
export const NEWSLETTER_LIST_FAIL = 'NEWSLETTER_LIST_FAIL';

export const NEWSLETTER_DELETE_REQUEST = 'NEWSLETTER_DELETE_REQUEST';
export const NEWSLETTER_DELETE_SUCCESS = 'NEWSLETTER_DELETE_SUCCESS';
export const NEWSLETTER_DELETE_FAIL = 'NEWSLETTER_DELETE_FAIL';
