export const CHAT_LIST_MY_REQUEST = 'CHAT_LIST_MY_REQUEST';
export const CHAT_LIST_MY_SUCCESS = 'CHAT_LIST_MY_SUCCESS';
export const CHAT_LIST_MY_FAIL = 'CHAT_LIST_MY_FAIL';

export const CHAT_HISTORY_REQUEST = 'CHAT_HISTORY_REQUEST';
export const CHAT_HISTORY_SUCCESS = 'CHAT_HISTORY_SUCCESS';
export const CHAT_HISTORY_FAIL = 'CHAT_HISTORY_FAIL';

export const CHAT_ADMIN_LIST_REQUEST = 'CHAT_ADMIN_LIST_REQUEST';
export const CHAT_ADMIN_LIST_SUCCESS = 'CHAT_ADMIN_LIST_SUCCESS';
export const CHAT_ADMIN_LIST_FAIL = 'CHAT_ADMIN_LIST_FAIL';

export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
export const CHAT_MARK_READ_REQUEST = 'CHAT_MARK_READ_REQUEST';
export const CHAT_MARK_READ_SUCCESS = 'CHAT_MARK_READ_SUCCESS';
export const CHAT_MARK_READ_FAIL = 'CHAT_MARK_READ_FAIL';

export const CHAT_OPEN_WITH_MESSAGE = 'CHAT_OPEN_WITH_MESSAGE';
export const CHAT_CLOSE = 'CHAT_CLOSE';

export const CHAT_MESSAGE_DELETE = 'CHAT_MESSAGE_DELETE';
export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE';
